spring:
  application:
    name: data-engine
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/demo_batch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  mongodb:
    uri: mongodb://localhost:27017/playground?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  batch:
    jdbc:
      initialize-schema: always
logging:
  level:
    org.mongodb.driver: DEBUG
nio:
  path-to-dir: /Users/arfalr/Documents/batch
  filename: transaction.csv